---
# Here we describe every software we may want to install
- hosts: all
  roles:
  - role: packages
    brew_taps:
    - homebrew/binary
    brew_packages:
    - heroku-toolbelt
    - ctags
    - imagemagick
    - cloc
    - ack
    - mercurial
    - bazaar
    - hub
    - direnv
    - git
    - git-flow-avh
    - tmux
    - docker
    - boot2docker
    - gist
    - reattach-to-user-namespace
    - packer
    - ngrok
    - awscli
    - maven
    - gradle
    - python
    - node
    - ruby
    - zsh
    - sslmate
    - lua
    - docker-compose
    - docker-machine
  - role: heroku_plugins
  - role: ruby_gems
  - role: npm_packages
  - role: vagrant_plugins
  - role: vim
  - role: powerline
  tasks:
    name: Install Golang
    homebrew: name=go state=latest install_options=--cross-compile-all
