---
# Here we describe every software we may want to install
- hosts: all
  roles:
  - role: osxc.packages
    brew_taps:
    - caskroom/fonts
    - homebrew/binary
    - caskroom/versions
    brew_packages:
    - fleetctl
    - ctags
    - imagemagick
    - cloc
    - ack
    - mercurial
    - bazaar
    - hub
    - direnv
    - git
    - git-flow-avh
    - tmux
    - docker
    - boot2docker
    - gist
    - reattach-to-user-namespace
    - packer
    - ngrok
    - awscli
    - android-sdk
    - maven
    - ant
    - gradle
    - python
    - node
    - ruby
    - jruby
    - legit
    - postgres
    - mongodb
    - redis
    - mariadb
    - zsh
    cask_packages:
    - font-source-code-pro
    - font-inconsolata-dz-for-powerline
    - font-symbola
    - java
    - alfred
    - intellij-idea
    - pycharm-ce
    - rubymine
    - sublime-text3
    - virtualbox
    - vmware-fusion
    - vagrant
    - horndis
    - skitch
    - dropbox
    - evernote
    - firefox
    - flash
    - google-chrome
    - google-hangouts
    - hipchat
    - libreoffice
    - reggy
    - skype
    - vlc
    - appcleaner
    - iterm2
    - remote-desktop-connection
    - joinme
    - silverlight
    - adobe-air
    - mono-mdk
    - onepassword
    - arduino-beta
    - chefdk
    - mailbox
  - role: heroku
  - role: ruby_gems
  - role: npm_packages
  - role: vagrant
  tasks:
    name: Install Golang
    homebrew: name=go state=latest install_options=--cross-compile-all
