---
- name: determine linked document location
  command: test -L ~/Documents
  ignore_errors: True
  register: doc_linked

- name: backup and move current documents
  command: sudo mv ~/Documents ~/Documents.backup
  ignore_errors: True
  when: doc_linked|failed

- name: symlink ~/Documents to dropbox
  file: state=link src="~/Dropbox/Documents" dest="~/Documents" force=true

- name: symlink ~/src to Happy
  file: state=link src="/Volumes/Happy/src" dest="~/src" force=true

- name: create ~/bin directory
  file: state=directory path="~/bin"