---
- name: determine linked document location
  command: test -L ~/Documents
  ignore_errors: True
  register: doc_linked

- name: backup and move current documents
  command: sudo mv ~/Documents ~/Documents.backup
  ignore_errors: True
  when: doc_linked|failed

- name: symlink ~/Documents to dropbox
  file: state=link src="~/Dropbox/Documents" dest="~/Documents" force=true

- name: create ~/Projects directory
  file: state=directory path="~/Projects"

- name: create ~/Golang directory
  file: state=directory path="~/Golang"
