---

- name: Clone oh-my-zsh
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=/Users/{{ ansible_user_id }}/.oh-my-zsh

- name: add homebrew zsh to /etc/shells
  lineinfile: dest=/etc/shells regexp="local" line="/usr/local/bin/zsh" state=present
  sudo: yes

- name: backup .zshrc
  command: rm ~/.zshrc
  ignore_errors: True

- name: copy oh-my-zsh template
  copy: src=/Users/{{ ansible_user_id }}/.oh-my-zsh/templates/zshrc.zsh-template dest=/Users/{{ ansible_user_id }}/.zshrc

- name: change shell
  command: chsh -s /usr/local/bin/zsh

- name: change oh-my-zsh plugin list
  lineinfile: dest=~/.zshrc regexp="^plugins=" line="plugins=(brew brew-cask git git-flow-avh osx vagrant)" state=present

- name: change prompt theme
  lineinfile: dest=~/.zshrc regexp="^ZSH_THEME=" line="ZSH_THEME=\"pygmalion\"" state=present
