---

- name: Install Dockutils
  git: repo=https://github.com/kcrawford/dockutil.git dest=/Users/{{ ansible_user_id }}/src/github.com/kcrawford/dockutil

- name: clean dock
  shell: "PYTHONIOENCODING=utf-8 {{ dockutil_exe }} --remove all creates=~/.managed-dock"

- name: flag managed dock
  file: path=~/.managed-dock state=touch

- name: add apps
  shell: "PYTHONIOENCODING=utf-8 {{ dockutil_exe }} --add '{{ item }}'"
  ignore_errors: True
  with_items: apps

- name: add folders
  shell: "PYTHONIOENCODING=utf-8 {{ dockutil_exe }} --add '{{ item.path }}' --view {{ item.view|default('grid') }} --display {{ item.display|default('folder') }} --sort {{ item.sort|default('name') }}"
  ignore_errors: True
  with_items: folders
  when: folders is defined